# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TaskDisplay.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(721, 382)
        Form.setStyleSheet("background : #2c2825;")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setStyleSheet("background: rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_2.setStyleSheet("background: rgb(255, 255, 255)")
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.gridLayout.addWidget(self.lcdNumber_2, 4, 1, 1, 1)
        self.BackButton = QtWidgets.QPushButton(Form)
        self.BackButton.setStyleSheet("background: rgb(255, 85, 0)")
        self.BackButton.setObjectName("BackButton")
        self.gridLayout.addWidget(self.BackButton, 5, 0, 1, 1)
        self.TaskName = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.TaskName.setFont(font)
        self.TaskName.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TaskName.setStyleSheet("color : rgb(236, 236, 236);")
        self.TaskName.setScaledContents(False)
        self.TaskName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.TaskName.setObjectName("TaskName")
        self.gridLayout.addWidget(self.TaskName, 0, 0, 1, 3)
        self.label = QtWidgets.QLabel(Form)
        self.label.setStyleSheet("background: rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setStyleSheet("background: rgb(0, 0, 0)")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 3)
        self.lcdNumber = QtWidgets.QLCDNumber(Form)
        self.lcdNumber.setStyleSheet("background: rgb(255, 255, 255)")
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 3, 1, 1, 1)
        self.TaskDeleteButton = QtWidgets.QPushButton(Form)
        self.TaskDeleteButton.setStyleSheet("background: #fdcb52;\n"
"")
        self.TaskDeleteButton.setObjectName("TaskDeleteButton")
        self.gridLayout.addWidget(self.TaskDeleteButton, 4, 2, 1, 1)
        self.TaskEditButton = QtWidgets.QPushButton(Form)
        self.TaskEditButton.setStyleSheet("background: #fdcb52;")
        self.TaskEditButton.setObjectName("TaskEditButton")
        self.gridLayout.addWidget(self.TaskEditButton, 5, 2, 1, 1)
        self.TaskCompleteButton = QtWidgets.QPushButton(Form)
        self.TaskCompleteButton.setStyleSheet("background: #fdcb52;\n"
"")
        self.TaskCompleteButton.setObjectName("TaskCompleteButton")
        self.gridLayout.addWidget(self.TaskCompleteButton, 3, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setStyleSheet("background: rgb(0, 0, 0)")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p>Days Left:</p></body></html>"))
        self.BackButton.setText(_translate("Form", "Back"))
        self.TaskName.setText(_translate("Form", "TaskName"))
        self.label.setText(_translate("Form", "Priority Level:"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Display Description</span></p></body></html>"))
        self.TaskDeleteButton.setText(_translate("Form", "Delete Task"))
        self.TaskEditButton.setText(_translate("Form", "Edit Task"))
        self.TaskCompleteButton.setText(_translate("Form", "Complete Task"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Display Labels</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
