# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TaskDisplay.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(588, 347)
        Form.setStyleSheet("background : #2c2825;")
        self.TaskName = QtWidgets.QLabel(Form)
        self.TaskName.setGeometry(QtCore.QRect(12, 12, 565, 37))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.TaskName.setFont(font)
        self.TaskName.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TaskName.setStyleSheet("color : rgb(236, 236, 236);")
        self.TaskName.setScaledContents(False)
        self.TaskName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.TaskName.setObjectName("TaskName")
        self.TaskDeleteButton = QtWidgets.QPushButton(Form)
        self.TaskDeleteButton.setGeometry(QtCore.QRect(456, 252, 121, 37))
        self.TaskDeleteButton.setStyleSheet("background: #fdcb52;\n"
"")
        self.TaskDeleteButton.setObjectName("TaskDeleteButton")
        self.TaskCompleteButton = QtWidgets.QPushButton(Form)
        self.TaskCompleteButton.setGeometry(QtCore.QRect(456, 204, 121, 37))
        self.TaskCompleteButton.setStyleSheet("background: #fdcb52;\n"
"")
        self.TaskCompleteButton.setObjectName("TaskCompleteButton")
        self.TaskEditButton = QtWidgets.QPushButton(Form)
        self.TaskEditButton.setGeometry(QtCore.QRect(456, 300, 121, 37))
        self.TaskEditButton.setStyleSheet("background: #fdcb52;")
        self.TaskEditButton.setObjectName("TaskEditButton")
        self.BackButton = QtWidgets.QPushButton(Form)
        self.BackButton.setGeometry(QtCore.QRect(12, 300, 109, 37))
        self.BackButton.setStyleSheet("background: rgb(255, 85, 0)")
        self.BackButton.setObjectName("BackButton")
        self.lcdNumber = QtWidgets.QLCDNumber(Form)
        self.lcdNumber.setGeometry(QtCore.QRect(120, 202, 85, 37))
        self.lcdNumber.setStyleSheet("background: rgb(255, 255, 255)")
        self.lcdNumber.setObjectName("lcdNumber")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(12, 203, 97, 37))
        self.label.setStyleSheet("background: rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_2.setGeometry(QtCore.QRect(120, 250, 85, 37))
        self.lcdNumber_2.setStyleSheet("background: rgb(255, 255, 255)")
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(12, 251, 97, 37))
        self.label_2.setStyleSheet("background: rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(12, 48, 565, 145))
        self.label_3.setStyleSheet("background: rgb(0, 0, 0)")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.TaskName.setText(_translate("Form", "TaskName"))
        self.TaskDeleteButton.setText(_translate("Form", "Delete Task"))
        self.TaskCompleteButton.setText(_translate("Form", "Complete Task"))
        self.TaskEditButton.setText(_translate("Form", "Edit Task"))
        self.BackButton.setText(_translate("Form", "Back"))
        self.label.setText(_translate("Form", "Priority Level:"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p>Days Left:</p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Display Description alongside the selected labels here</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
