# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LabelEditor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class LabelWidgetUI(object):
    def setupUi(self, Dialog):
        '''
        Dialog.setObjectName("Dialog")
        Dialog.resize(722, 380)
        '''
        Dialog.setStyleSheet("background: #03fccf")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(3, 6, 709, 373))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMaximumSize(QtCore.QSize(683, 29))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.LabelNameEdit = QtWidgets.QLineEdit(self.widget)
        self.LabelNameEdit.setMinimumSize(QtCore.QSize(697, 97))
        self.LabelNameEdit.setObjectName("LabelNameEdit")
        self.verticalLayout.addWidget(self.LabelNameEdit)
        self.EditColorButton = QtWidgets.QPushButton(self.widget)
        self.EditColorButton.setObjectName("EditColorButton")
        self.EditColorButton.clicked.connect(self.colour)
        self.verticalLayout.addWidget(self.EditColorButton)
        self.ChangeNameButton=QtWidgets.QPushButton(self.widget)
        self.ChangeNameButton.setObjectName("ChangeNameButton")
        self.verticalLayout.addWidget(self.ChangeNameButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def colour(self):
        return QtWidgets.QColorDialog.getColor()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt;\">Label Name:</span></p></body></html>"))
        self.EditColorButton.setText(_translate("Dialog", "Label Colour Picker"))
        self.ChangeNameButton.setText(_translate("Dialog","Change Title"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = LabelWidgetUI()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
