# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(720, 380)
        Dialog.setStyleSheet("background: #03fccf")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 4, 709, 373))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 389, 369))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 1, 3, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.push1 = QtWidgets.QPushButton(self.widget)
        self.push1.setObjectName("push1")
        self.push1.clicked.connect(self.colour)
        self.verticalLayout.addWidget(self.push1)
        self.push2 = QtWidgets.QPushButton(self.widget)
        self.push2.setObjectName("push2")
        self.push2.clicked.connect(self.colour)
        self.verticalLayout.addWidget(self.push2)
        self.push3 = QtWidgets.QPushButton(self.widget)
        self.push3.setObjectName("push3")
        self.push3.clicked.connect(self.colour)
        self.verticalLayout.addWidget(self.push3)
        self.push4 = QtWidgets.QPushButton(self.widget)
        self.push4.setObjectName("push4")
        self.push4.clicked.connect(self.colour)
        self.verticalLayout.addWidget(self.push4)
        self.push5 = QtWidgets.QPushButton(self.widget)
        self.push5.setObjectName("push5")
        self.push5.clicked.connect(self.colour)
        self.verticalLayout.addWidget(self.push5)
        self.push6 = QtWidgets.QPushButton(self.widget)
        self.push6.setObjectName("push6")
        self.push6.clicked.connect(self.colour)
        self.verticalLayout.addWidget(self.push6)
        self.push7 = QtWidgets.QPushButton(self.widget)
        self.push7.setObjectName("push7")
        self.push7.clicked.connect(self.colour)
        self.verticalLayout.addWidget(self.push7)
        self.push8 = QtWidgets.QPushButton(self.widget)
        self.push8.setObjectName("push8")
        self.push8.clicked.connect(self.colour)
        self.verticalLayout.addWidget(self.push8)
        self.push9 = QtWidgets.QPushButton(self.widget)
        self.push9.setObjectName("push9")
        self.push9.clicked.connect(self.colour)
        self.verticalLayout.addWidget(self.push9)
        self.push10 = QtWidgets.QPushButton(self.widget)
        self.push10.setObjectName("push10")
        self.push10.clicked.connect(self.colour)
        self.verticalLayout.addWidget(self.push10)
        self.gridLayout.addLayout(self.verticalLayout, 0, 2, 3, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.colour)
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def colour(self):
        color = QtWidgets.QColorDialog.getColor()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:24pt;\">Labels:</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt;\">Priority colours:</span></p></body></html>"))
        self.push1.setText(_translate("Dialog", "1"))
        self.push2.setText(_translate("Dialog", "2"))
        self.push3.setText(_translate("Dialog", "3"))
        self.push4.setText(_translate("Dialog", "4"))
        self.push5.setText(_translate("Dialog", "5"))
        self.push6.setText(_translate("Dialog", "6"))
        self.push7.setText(_translate("Dialog", "7"))
        self.push8.setText(_translate("Dialog", "8"))
        self.push9.setText(_translate("Dialog", "9"))
        self.push10.setText(_translate("Dialog", "10"))
        self.pushButton.setText(_translate("Dialog", "Main Window Colour"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
